### PR TITLE
Addition of unzip (for windows), bird and cloud options. LT5 and LT7 download capability

### PR DESCRIPTION
**Pull request by vascobnunes**
I added the following options:

 - z - to unzip downloaded tgz files. Uses the tartool (https://tartool.codeplex.com/)
 - b - which lets you select the product you're looking for (LT5, LE7 or LC8)
 - c - which lets you define a cloud cover limit for the downloaded images. If an image is found with clouds below the limit the script stops looking for more images within the time interval. If not, it doesn't keep the image and tries to find another.

Landsat 5 and Landsat 7 download wasn't working (at least for me). I fixed that.

The connection to earthexplorer was established within the while loop, so it was repeating it for each iteration. I moved that block to before the while loop, making the process much faster.

### CODE REVIEW

**Comment by olivierhagolle** [comment]
Very nice improvements, I just merged the codes. Thanks a lot !

**Comment by vascobnunes** [comment]
Cool! My first contributions to some useful github project :)

**Comment by olivierhagolle** [comment]
Yes cool, it was my first github too, and given the contributions it yielded, I'll do that again.
I have made a few changes in my version, having known some difficulties with Landsat 7 in my tests.
You might need to integrate them in your version. 
I also went back with my way of using directories,as I am downloading images from various sites.
Best regards,
Olivier

**Comment by vascobnunes** [comment]
I'm not sure how to integrate your changes to my fork... I need to investigate that. but yes, I will.
When you say you went back on your way of using directories, thats only for the -list option, right?
Regards.
Vasco

**Comment by vascobnunes** [comment]
Ok, I got what you meant with the "directories". And also managed to merge your changes into my fork. 
Any next steps? :)

**Comment by vascobnunes** [comment]
What about creating a release? :)
https://help.github.com/articles/creating-releases/

**Pull request merged**
